language: java
jdk:
- oraclejdk11
addons:
  apt:
    packages:
    - python2.7
branches:
  except:
  - /^untagged/
before_script:
- unset _JAVA_OPTIONS
- pip install AdvancedHTMLParser --user
- export TRAVIS_TAG=`python getlink.py ver`
script:
- bash deploy.sh
before_deploy:
# # Set up git user name and tag this commit
# - git config --local user.name "xiaoxx_travis"
# - git config --local user.email "me@xiaoxx.cc"
# - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
  - mipay-*.zip
  - eufix-*.zip
  - weather-*.apk
  overwrite: true
  skip_cleanup: true
  on:
    repo: xiaoxx970/mipay-extract
    tags: true
